name: Google Cloud Run Deploy
# https://github.com/google-github-actions/setup-gcloud
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: amg-pwa-v2

jobs:
  deploy-gcr:
    name: Deploy to GCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCR_SA_KEY }}
          project_id: ${{ secrets.GCR_PROJECT }}
          export_default_credentials: true
      - name: Configure docker for GCP
        run: gcloud auth configure-docker          

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/$PROJECT_ID/$SERVICE_NAME:latest
          build-args: |
            HTTP_PORT=3000

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/$PROJECT_ID/$SERVICE_NAME:latest
          service: $SERVICE_NAME
          region: $RUN_REGION
          platform: managed
          allow-unauthenticated: true
